version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - cyclop
    - depguard
    - dogsled
    - dupword
    - dupl
    - err113
    - errorlint
    - exhaustive
    - embeddedstructfieldcheck
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - gosmopolitan
    - govet
    - inamedparam
    - intrange
    - ireturn
    - lll
    - maintidx
    - makezero
    - mirror
    - mnd
    - modernize
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - recvcheck
    - revive
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - errchkjson
          - forcetypeassert
        path: /*_test.go
      - linters:
          - forbidigo
        path: /*_example_test.go
